name: Generar Sitemap Automático

on:
  push:
    branches:
      - main # Cambia a 'master' o 'gh-pages' si tu rama por defecto es otra

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Generar el archivo sitemap.xml
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://marianoman842.github.io/Prueba-Sinonimia/ # Cambia esto por la URL real de tu web

    - name: Hacer commit y push del sitemap generado
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add sitemap.xml
        # El condicional evita que falle la acción si el sitemap no ha cambiado
        git diff-index --quiet HEAD || git commit -m "Automated sitemap update"
        git push
